[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "plancosts"
version = "0.0.0"
description = "Terraform plan cost reporter"
readme = "readme.md"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
include = ["plancosts*"]