name: Upload Release Asset (Python)

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build sdist and wheel
        run: python -m build

      - name: Create Release (published)
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false          # <-- must be public for Homebrew
          prerelease: false

      - name: Resolve artifact paths
        id: artifacts
        shell: bash
        run: |
          echo "wheel=$(ls dist/*.whl | head -n1)" >> $GITHUB_OUTPUT
          echo "sdist=$(ls dist/*.tar.gz | head -n1)" >> $GITHUB_OUTPUT

      - name: Upload wheel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.artifacts.outputs.wheel }}
          asset_name: plancosts-${{ github.ref_name }}.whl
          asset_content_type: application/octet-stream

      - name: Upload sdist
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.artifacts.outputs.sdist }}
          asset_name: plancosts-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_RELEASE_TOKEN }}
          formula: infracost

