name: Publish to DockerHub

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"

jobs:
  dockerhub:
    name: Build and Push to DockerHub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPOSITORY }}:latest,${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
          build-args: |
            TERRAFORM_VERSION=0.12.25
