name: Python CI

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'requirements*.txt'
      - 'Makefile'
      - '.github/workflows/python.yml'
      - 'test_plan*.json'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        shell: bash
        run: |
          python -m pip install -U pip
          if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi
          pip install black isort ruff mypy pytest build wheel
          # If you have packaging metadata, install editable; else set PYTHONPATH
          if [[ -f plancosts/pyproject.toml || -f plancosts/setup.py || -f plancosts/setup.cfg ]]; then
            pip install -e ./plancosts
          else
            echo "PYTHONPATH=$GITHUB_WORKSPACE/plancosts:$GITHUB_WORKSPACE:$PYTHONPATH" >> $GITHUB_ENV
          fi
          if grep -qE '^[[:space:]]*deps:' Makefile 2>/dev/null; then make deps || true; fi

      - name: Static checks (format + lint + typecheck)
        shell: bash
        run: |
          if [[ -f Makefile ]]; then
            make fmt
            make lint || true
            make typecheck || true
          else
            black .
            isort .
            ruff check . || true
            mypy plancosts || true
          fi

      - name: Unit tests
        shell: bash
        run: |
          if [[ -f Makefile ]]; then
            make test
          else
            pytest -q
          fi

      - name: Start mock pricing API (background)
        shell: bash
        run: |
          # Run server only (no SELF_TEST), in background
          python -m plancosts.tests.mock_price &
          # Wait for port 4000 to be ready
          for i in $(seq 1 30); do
            if curl -sSf http://127.0.0.1:4000/ >/dev/null 2>&1; then
              echo "Mock API is up."
              break
            fi
            sleep 0.5
          done
          # Final sanity ping
          curl -sSf http://127.0.0.1:4000/

      - name: CLI smoke with fixtures (table)
        env:
          PLANCOSTS_API_URL: http://127.0.0.1:4000
        shell: bash
        run: |
          test -f plancosts/main.py || (echo "plancosts/main.py missing" && exit 1)
          if [[ -f "plancosts/test_plan_ern.json" ]]; then python plancosts/main.py --tfjson plancosts/test_plan_ern.json -o table; fi
          if [[ -f "plancosts/test_plan_rds.json" ]]; then python plancosts/main.py --tfjson plancosts/test_plan_rds.json -o table; fi
          if [[ -f "plancosts/test_plan.json" ]]; then python plancosts/main.py --tfjson plancosts/test_plan.json -o table; fi
